server:
  port: 8888
spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: file:///F:/video tutorials/tutorials-workspace/spring-cloud-config/config-repository
